using System.Globalization;

namespace RobocopySafe.Core;

public enum UiLanguage
{
    System,
    SimplifiedChinese,
    English,
}

public enum TextId
{
    WindowTitle,
    LanguageSystem,
    LanguageChinese,
    LanguageEnglish,
    SourceLabel,
    DestinationLabel,
    OperationLabel,
    LinkLabel,
    ThreadsLabel,
    RetriesLabel,
    WaitLabel,
    FilePatternsLabel,
    DirectoryPatternsLabel,
    CommandPreviewLabel,
    ExecutionLogLabel,
    OperationCopy,
    OperationMove,
    LinkSkip,
    LinkCopy,
    LinkFollow,
    ExcludeHiddenSystemFiles,
    ExcludeHiddenSystemDirectories,
    SourcePlaceholder,
    DestinationPlaceholder,
    ExcludedFilesPlaceholder,
    ExcludedDirectoriesPlaceholder,
    Browse,
    StartCopy,
    StartMove,
    Preview,
    Cancel,
    Logs,
    InstallContextMenu,
    RemoveContextMenu,
    Ready,
    ToolTipSourceBrowse,
    ToolTipDestinationBrowse,
    ToolTipExcludeFiles,
    ToolTipExcludeDirectories,
    ToolTipLinkHandling,
    ToolTipExcludedFiles,
    ToolTipExcludedDirectories,
    ToolTipPreview,
    ToolTipOpenLogs,
    ToolTipContextMenu,
    ToolTipLanguage,
    ClipboardCutLoaded,
    ClipboardCopyLoaded,
    FollowWarning,
    SelectDestinationDialog,
    SelectSourceDialog,
    ScanningExclusions,
    LogPreview,
    LogStart,
    LogExcludedCount,
    PrefixWarning,
    StatusPreviewing,
    StatusExecuting,
    LogCanceled,
    StatusCanceled,
    LogCompleteExit,
    StatusPreviewComplete,
    StatusOperationComplete,
    LogFailedExit,
    StatusFailedExit,
    PrefixError,
    CannotExecuteTitle,
    LogEmptySourceDeleted,
    LogSourceRemoved,
    LogRootPreserved,
    LogClipboardCleared,
    LogClipboardClearFailed,
    LogResidualNotice,
    LogResidualItems,
    LogResidualCheckError,
    LogResidualClipboard,
    LogResidualManual,
    StatusMovePartial,
    MoveConfirmMessage,
    MoveConfirmTitle,
    StatusCanceling,
    ProcessPathUnavailable,
    ContextRemoveConfirmMessage,
    ContextRemoveTitle,
    StatusContextRemoved,
    StatusContextInstalled,
    ContextConfigFailedTitle,
    StatusContextFailed,
    LogUiOmitted,
    VerbPreviewing,
    VerbCopying,
    StatusCurrentProgress,
    StatusOutputProgress,
    LogTrimmedNotice,
    CloseRunningMessage,
    CloseConfirmTitle,
    SourceDirectoryName,
    PasteTargetDirectoryName,
    ExcludedFilesName,
    ExcludedDirectoriesName,
    UnknownLinkHandling,
    TooManyExclusions,
    CannotReadDirectory,
    CannotReadDirectoryAttributes,
    MoveFollowForbidden,
    RootLinkForbidden,
    OptionLikeExclusion,
    SelectNamedDirectory,
    NamedDirectoryMissing,
    SelectDestinationDirectory,
    SameSourceDestination,
    DestinationInsideSource,
    CannotStartRobocopy,
    ClipboardNoPasteDirectory,
    MoveIntoSelf,
    ClipboardSourceMissing,
    ClipboardNoDirectory,
    ClipboardMultipleItems,
    CopySuffix,
    CopySuffixIndexed,
    ModeOnlyCopyMove,
    SpecialActionsConflict,
    StageRequiresMode,
    PasteCannotCombine,
    OptionMissingValue,
    ContextTargetMissing,
    RegistryCreateFailed,
    ContextCommandCreateFailed,
    ContextCommandLineCreateFailed,
    ContextMenuTitle,
    ContextCopyThisDirectory,
    ContextCopyCurrentDirectory,
    ContextCutThisDirectory,
    ContextCutCurrentDirectory,
    ContextPasteThisDirectory,
    ContextPasteCurrentDirectory,
    ContextOpen,
    UnknownOption,
    HelpText,
    VersionText,
}

public static class AppText
{
    public static UiLanguage LanguagePreference { get; private set; } = UiLanguage.System;

    public static CultureInfo Culture { get; private set; } = ResolveCulture(UiLanguage.System);

    public static void SetLanguage(UiLanguage language)
    {
        LanguagePreference = Enum.IsDefined(language) ? language : UiLanguage.System;
        Culture = ResolveCulture(LanguagePreference);
    }

    public static string Get(TextId id) => IsChinese ? GetChinese(id) : GetEnglish(id);

    public static string Format(TextId id, params object?[] arguments) =>
        string.Format(Culture, Get(id), arguments);

    private static bool IsChinese =>
        string.Equals(Culture.TwoLetterISOLanguageName, "zh", StringComparison.OrdinalIgnoreCase);

    private static CultureInfo ResolveCulture(UiLanguage language) => language switch
    {
        UiLanguage.SimplifiedChinese => CultureInfo.GetCultureInfo("zh-CN"),
        UiLanguage.English => CultureInfo.GetCultureInfo("en-US"),
        _ when string.Equals(
            CultureInfo.CurrentUICulture.TwoLetterISOLanguageName,
            "zh",
            StringComparison.OrdinalIgnoreCase) => CultureInfo.GetCultureInfo("zh-CN"),
        _ => CultureInfo.GetCultureInfo("en-US"),
    };

    private static string GetEnglish(TextId id) => id switch
    {
        TextId.WindowTitle => "Robocopy Safe Copy",
        TextId.LanguageSystem => "System default",
        TextId.LanguageChinese => "简体中文",
        TextId.LanguageEnglish => "English",
        TextId.SourceLabel => "Source",
        TextId.DestinationLabel => "Destination",
        TextId.OperationLabel => "Operation",
        TextId.LinkLabel => "Links",
        TextId.ThreadsLabel => "Threads",
        TextId.RetriesLabel => "Retries",
        TextId.WaitLabel => "Wait",
        TextId.FilePatternsLabel => "Files",
        TextId.DirectoryPatternsLabel => "Directories",
        TextId.CommandPreviewLabel => "Command preview",
        TextId.ExecutionLogLabel => "Execution log",
        TextId.OperationCopy => "Copy",
        TextId.OperationMove => "Move",
        TextId.LinkSkip => "Skip links (recommended)",
        TextId.LinkCopy => "Copy link nodes",
        TextId.LinkFollow => "Follow link targets",
        TextId.ExcludeHiddenSystemFiles => "Exclude hidden/system files",
        TextId.ExcludeHiddenSystemDirectories => "Exclude hidden/system directories",
        TextId.SourcePlaceholder => "Select the source folder",
        TextId.DestinationPlaceholder => "Select the destination folder",
        TextId.ExcludedFilesPlaceholder => "Example: *.tmp;thumbs.db",
        TextId.ExcludedDirectoriesPlaceholder => "Example: $RECYCLE.BIN;System Volume Information",
        TextId.Browse => "Browse",
        TextId.StartCopy => "Start copy",
        TextId.StartMove => "Start move",
        TextId.Preview => "Preview",
        TextId.Cancel => "Cancel",
        TextId.Logs => "Logs",
        TextId.InstallContextMenu => "Install menu",
        TextId.RemoveContextMenu => "Remove menu",
        TextId.Ready => "Ready",
        TextId.ToolTipSourceBrowse => "Select the source directory.",
        TextId.ToolTipDestinationBrowse => "Select the destination directory.",
        TextId.ToolTipExcludeFiles => "Use /XA:SH to exclude files with Hidden or System attributes.",
        TextId.ToolTipExcludeDirectories => "Scan directory attributes before execution and add top-level hidden/system directories to /XD.",
        TextId.ToolTipLinkHandling => "Skipping is safest. /SJ and /SL preserve link nodes. Following targets may copy outside the source tree and is blocked for moves.",
        TextId.ToolTipExcludedFiles => "Separate values with semicolons or line breaks. Supports * and ? wildcards and passes them to /XF.",
        TextId.ToolTipExcludedDirectories => "Separate values with semicolons or line breaks. Supports names, relative paths, absolute paths, and wildcards.",
        TextId.ToolTipPreview => "Use Robocopy /L to list planned work without writing to the destination.",
        TextId.ToolTipOpenLogs => "Open the logs directory under Local AppData.",
        TextId.ToolTipContextMenu => "Install or remove the classic Explorer context menu for the current user.",
        TextId.ToolTipLanguage => "Choose the interface and Explorer menu language.",
        TextId.ClipboardCutLoaded => "Loaded a cut operation from the clipboard. Review it before moving.",
        TextId.ClipboardCopyLoaded => "Loaded a copy operation from the clipboard. Review it before copying.",
        TextId.FollowWarning => "Caution: following link targets may copy outside the source tree; move operations are blocked.",
        TextId.SelectDestinationDialog => "Select destination directory",
        TextId.SelectSourceDialog => "Select source directory",
        TextId.ScanningExclusions => "Scanning excluded directories...",
        TextId.LogPreview => "[Preview] The destination will not be modified.",
        TextId.LogStart => "[Run] Processing started.",
        TextId.LogExcludedCount => "[Exclusions] Discovered {0:N0} directories automatically.",
        TextId.PrefixWarning => "[Warning] {0}",
        TextId.StatusPreviewing => "Previewing...",
        TextId.StatusExecuting => "Running...",
        TextId.LogCanceled => "[Canceled] The operation was stopped by the user.",
        TextId.StatusCanceled => "Canceled",
        TextId.LogCompleteExit => "[Complete] Robocopy exit code {0} (codes 0-7 do not indicate a copy failure).",
        TextId.StatusPreviewComplete => "Preview complete",
        TextId.StatusOperationComplete => "Operation complete",
        TextId.LogFailedExit => "[Failed] Robocopy exit code {0}.",
        TextId.StatusFailedExit => "Operation failed, exit code {0}",
        TextId.PrefixError => "[Error] {0}",
        TextId.CannotExecuteTitle => "Unable to run",
        TextId.LogEmptySourceDeleted => "[Complete] Removed the empty source directory left after the move.",
        TextId.LogSourceRemoved => "[Complete] The source directory and processed contents were removed.",
        TextId.LogRootPreserved => "[Complete] The source was a drive root, so the root itself was preserved.",
        TextId.LogClipboardCleared => "[Complete] Cleared the completed move from the clipboard.",
        TextId.LogClipboardClearFailed => "[Notice] The source was removed, but the clipboard item could not be cleared automatically.",
        TextId.LogResidualNotice => "[Notice] Robocopy reported no write failure, but the source still contains unprocessed items: {0}",
        TextId.LogResidualItems => "[Remaining] Top-level items: {0}{1}",
        TextId.LogResidualCheckError => "[Remaining] Could not inspect or remove the source directory: {0}",
        TextId.LogResidualClipboard => "[Remaining] Common causes are exclusions, open files, or permissions. The clipboard was preserved so you can retry.",
        TextId.LogResidualManual => "[Remaining] Common causes are exclusions, open files, or permissions. Review the source and retry.",
        TextId.StatusMovePartial => "Move partially complete: source still contains items",
        TextId.MoveConfirmMessage => "A move deletes source files and directories after they are copied successfully.\n\nSource: {0}\nDestination: {1}\n\nContinue?",
        TextId.MoveConfirmTitle => "Confirm move",
        TextId.StatusCanceling => "Canceling...",
        TextId.ProcessPathUnavailable => "Unable to determine the application path.",
        TextId.ContextRemoveConfirmMessage => "Remove the Robocopy Safe Copy context menu for the current user?",
        TextId.ContextRemoveTitle => "Remove context menu",
        TextId.StatusContextRemoved => "Explorer context menu removed.",
        TextId.StatusContextInstalled => "Classic Explorer context menu installed.",
        TextId.ContextConfigFailedTitle => "Context menu configuration failed",
        TextId.StatusContextFailed => "Context menu configuration failed.",
        TextId.LogUiOmitted => "[UI] Omitted {0:N0} lines during high-volume output; the disk log still contains all meaningful output.",
        TextId.VerbPreviewing => "Previewing",
        TextId.VerbCopying => "Copying",
        TextId.StatusCurrentProgress => "{0} | current file {1}% | completed {2:N0} | {3}",
        TextId.StatusOutputProgress => "{0} | output {1:N0} lines | {2}",
        TextId.LogTrimmedNotice => "[UI] Older output was removed from the window. The complete meaningful output remains in the disk log.",
        TextId.CloseRunningMessage => "A copy is still running. Closing the window will terminate the current Robocopy process.",
        TextId.CloseConfirmTitle => "Confirm close",
        TextId.SourceDirectoryName => "source directory",
        TextId.PasteTargetDirectoryName => "paste target directory",
        TextId.ExcludedFilesName => "excluded file",
        TextId.ExcludedDirectoriesName => "excluded directory",
        TextId.UnknownLinkHandling => "Unknown link handling policy.",
        TextId.TooManyExclusions => "The exclusion list makes the command too long. Use broader names or wildcards and try again.",
        TextId.CannotReadDirectory => "Directory could not be read and was excluded: {0} ({1})",
        TextId.CannotReadDirectoryAttributes => "Directory attributes could not be read and the directory was excluded: {0} ({1})",
        TextId.MoveFollowForbidden => "Move cannot follow link targets because it could delete files outside the source tree. Skip links or copy link nodes instead.",
        TextId.RootLinkForbidden => "The source directory itself is a link or junction. Robocopy does not apply skip/copy-link rules to the root link. Select the real directory, or explicitly follow the target for a copy operation only.",
        TextId.OptionLikeExclusion => "An {0} value cannot start with '/', because Robocopy may parse it as an option: {1}",
        TextId.SelectNamedDirectory => "Select the {0}.",
        TextId.NamedDirectoryMissing => "The {0} does not exist: {1}",
        TextId.SelectDestinationDirectory => "Select the destination directory.",
        TextId.SameSourceDestination => "Source and destination cannot be the same directory.",
        TextId.DestinationInsideSource => "The destination cannot be inside the source directory because the copy would recurse into itself.",
        TextId.CannotStartRobocopy => "Unable to start robocopy.exe.",
        TextId.ClipboardNoPasteDirectory => "The clipboard does not contain a directory that can be pasted.",
        TextId.MoveIntoSelf => "The source is already in this destination and cannot be moved into itself.",
        TextId.ClipboardSourceMissing => "The clipboard source directory no longer exists: {0}",
        TextId.ClipboardNoDirectory => "The clipboard does not contain a directory. Use Copy/Cut in Explorer or the Robocopy Safe Copy context menu first.",
        TextId.ClipboardMultipleItems => "This version handles one directory at a time, but the clipboard contains {0:N0} items.",
        TextId.CopySuffix => "{0} - Copy",
        TextId.CopySuffixIndexed => "{0} - Copy ({1})",
        TextId.ModeOnlyCopyMove => "--mode accepts only copy or move.",
        TextId.SpecialActionsConflict => "Install, uninstall, stage, paste, help, and version actions cannot be combined.",
        TextId.StageRequiresMode => "--stage-source also requires --mode copy or move.",
        TextId.PasteCannotCombine => "--paste-to cannot be combined with source, destination, or mode options.",
        TextId.OptionMissingValue => "{0} requires a value.",
        TextId.ContextTargetMissing => "The context menu target application does not exist.",
        TextId.RegistryCreateFailed => "Unable to create registry key: HKCU\\{0}",
        TextId.ContextCommandCreateFailed => "Unable to create context menu command: {0}",
        TextId.ContextCommandLineCreateFailed => "Unable to create the command line for context menu command: {0}",
        TextId.ContextMenuTitle => "Robocopy Safe Copy",
        TextId.ContextCopyThisDirectory => "Copy this directory",
        TextId.ContextCopyCurrentDirectory => "Copy current directory",
        TextId.ContextCutThisDirectory => "Cut this directory",
        TextId.ContextCutCurrentDirectory => "Cut current directory",
        TextId.ContextPasteThisDirectory => "Paste into this directory...",
        TextId.ContextPasteCurrentDirectory => "Paste into current directory...",
        TextId.ContextOpen => "Open Safe Copy...",
        TextId.UnknownOption => "Unknown option: {0}",
        TextId.HelpText => "Usage:\n  {0} [--source <path>] [--destination <path>] [--mode copy|move]\n  {0} --install-context-menu\n  {0} --uninstall-context-menu\n  {0} --stage-source <path> --mode copy|move\n  {0} --paste-to <path>\n  {0} --help | --version",
        TextId.VersionText => "{0} version {1}",
        _ => throw new ArgumentOutOfRangeException(nameof(id), id, null),
    };

    private static string GetChinese(TextId id) => id switch
    {
        TextId.WindowTitle => "Robocopy 安全复制",
        TextId.LanguageSystem => "跟随系统",
        TextId.LanguageChinese => "简体中文",
        TextId.LanguageEnglish => "English",
        TextId.SourceLabel => "来源",
        TextId.DestinationLabel => "目标",
        TextId.OperationLabel => "操作",
        TextId.LinkLabel => "链接",
        TextId.ThreadsLabel => "线程",
        TextId.RetriesLabel => "重试",
        TextId.WaitLabel => "等待",
        TextId.FilePatternsLabel => "文件",
        TextId.DirectoryPatternsLabel => "目录",
        TextId.CommandPreviewLabel => "命令预览",
        TextId.ExecutionLogLabel => "执行日志",
        TextId.OperationCopy => "复制",
        TextId.OperationMove => "移动",
        TextId.LinkSkip => "跳过链接（推荐）",
        TextId.LinkCopy => "复制链接本身",
        TextId.LinkFollow => "跟随链接目标",
        TextId.ExcludeHiddenSystemFiles => "排除隐藏/系统文件",
        TextId.ExcludeHiddenSystemDirectories => "排除隐藏/系统目录",
        TextId.SourcePlaceholder => "选择要复制的源文件夹",
        TextId.DestinationPlaceholder => "选择接收文件的目标文件夹",
        TextId.ExcludedFilesPlaceholder => "例如：*.tmp;thumbs.db",
        TextId.ExcludedDirectoriesPlaceholder => "例如：$RECYCLE.BIN;System Volume Information",
        TextId.Browse => "浏览",
        TextId.StartCopy => "开始复制",
        TextId.StartMove => "开始移动",
        TextId.Preview => "预览",
        TextId.Cancel => "取消",
        TextId.Logs => "日志",
        TextId.InstallContextMenu => "安装右键",
        TextId.RemoveContextMenu => "移除右键",
        TextId.Ready => "就绪",
        TextId.ToolTipSourceBrowse => "选择源目录。",
        TextId.ToolTipDestinationBrowse => "选择目标目录。",
        TextId.ToolTipExcludeFiles => "使用 /XA:SH 排除带 Hidden 或 System 属性的文件。",
        TextId.ToolTipExcludeDirectories => "执行前扫描目录属性，并把顶层隐藏/系统目录加入 /XD。",
        TextId.ToolTipLinkHandling => "跳过链接最安全；/SJ 和 /SL 保留链接节点；跟随目标可能复制源树外的数据，移动时会被阻止。",
        TextId.ToolTipExcludedFiles => "使用分号或换行分隔，支持 * 和 ? 通配符，并传递给 /XF。",
        TextId.ToolTipExcludedDirectories => "使用分号或换行分隔，支持目录名、相对路径、绝对路径和通配符。",
        TextId.ToolTipPreview => "使用 Robocopy /L 列出将处理的内容，不写入目标目录。",
        TextId.ToolTipOpenLogs => "打开 LocalAppData 下的日志目录。",
        TextId.ToolTipContextMenu => "为当前用户安装或移除经典资源管理器右键菜单。",
        TextId.ToolTipLanguage => "选择界面和资源管理器右键菜单语言。",
        TextId.ClipboardCutLoaded => "已从剪贴板加载剪切操作，请确认后开始移动。",
        TextId.ClipboardCopyLoaded => "已从剪贴板加载复制操作，请确认后开始复制。",
        TextId.FollowWarning => "注意：跟随链接目标可能复制源目录树之外的数据；移动操作会被阻止。",
        TextId.SelectDestinationDialog => "选择目标目录",
        TextId.SelectSourceDialog => "选择源目录",
        TextId.ScanningExclusions => "正在扫描排除目录...",
        TextId.LogPreview => "[预览] 不会写入目标目录。",
        TextId.LogStart => "[执行] 开始处理。",
        TextId.LogExcludedCount => "[排除] 自动发现 {0:N0} 个目录。",
        TextId.PrefixWarning => "[警告] {0}",
        TextId.StatusPreviewing => "正在预览...",
        TextId.StatusExecuting => "正在执行...",
        TextId.LogCanceled => "[取消] 操作已由用户停止。",
        TextId.StatusCanceled => "已取消",
        TextId.LogCompleteExit => "[完成] Robocopy 返回码 {0}（成功：0-7 均不表示失败）。",
        TextId.StatusPreviewComplete => "预览完成",
        TextId.StatusOperationComplete => "操作完成",
        TextId.LogFailedExit => "[失败] Robocopy 返回码 {0}。",
        TextId.StatusFailedExit => "操作失败，返回码 {0}",
        TextId.PrefixError => "[错误] {0}",
        TextId.CannotExecuteTitle => "无法执行",
        TextId.LogEmptySourceDeleted => "[完成] 已删除移动后留下的空源目录。",
        TextId.LogSourceRemoved => "[完成] 源目录及已处理内容已移除。",
        TextId.LogRootPreserved => "[完成] 源为磁盘根目录，根目录本身已保留。",
        TextId.LogClipboardCleared => "[完成] 已清除完成移动的剪贴板项目。",
        TextId.LogClipboardClearFailed => "[提示] 源已移除，但未能自动清除剪贴板项目。",
        TextId.LogResidualNotice => "[注意] 目标写入未发生 Robocopy 失败，但源目录仍有未处理内容：{0}",
        TextId.LogResidualItems => "[残留] 顶层项目：{0}{1}",
        TextId.LogResidualCheckError => "[残留] 检查或删除源目录时出错：{0}",
        TextId.LogResidualClipboard => "[残留] 常见原因是排除规则、文件占用或权限限制；剪贴板已保留，可处理后重试。",
        TextId.LogResidualManual => "[残留] 常见原因是排除规则、文件占用或权限限制，请检查后重试。",
        TextId.StatusMovePartial => "移动部分完成：源目录仍有内容",
        TextId.MoveConfirmMessage => "移动会在复制成功后删除源文件和目录。\n\n源：{0}\n目标：{1}\n\n确认继续？",
        TextId.MoveConfirmTitle => "确认移动",
        TextId.StatusCanceling => "正在取消...",
        TextId.ProcessPathUnavailable => "无法确定程序路径。",
        TextId.ContextRemoveConfirmMessage => "确认移除当前用户的 Robocopy 安全复制右键菜单？",
        TextId.ContextRemoveTitle => "移除右键菜单",
        TextId.StatusContextRemoved => "右键菜单已移除。",
        TextId.StatusContextInstalled => "经典资源管理器右键菜单已安装。",
        TextId.ContextConfigFailedTitle => "右键菜单配置失败",
        TextId.StatusContextFailed => "右键菜单配置失败。",
        TextId.LogUiOmitted => "[界面] 高速输出期间省略 {0:N0} 行；磁盘日志仍完整保留有效输出。",
        TextId.VerbPreviewing => "正在预览",
        TextId.VerbCopying => "正在复制",
        TextId.StatusCurrentProgress => "{0} | 当前文件 {1}% | 完成项 {2:N0} | {3}",
        TextId.StatusOutputProgress => "{0} | 输出 {1:N0} 行 | {2}",
        TextId.LogTrimmedNotice => "[界面] 较早输出已从窗口移除，完整有效输出保存在磁盘日志。",
        TextId.CloseRunningMessage => "复制仍在执行。关闭窗口会终止当前 Robocopy 进程。",
        TextId.CloseConfirmTitle => "确认关闭",
        TextId.SourceDirectoryName => "源目录",
        TextId.PasteTargetDirectoryName => "粘贴目标目录",
        TextId.ExcludedFilesName => "排除文件",
        TextId.ExcludedDirectoriesName => "排除目录",
        TextId.UnknownLinkHandling => "未知的链接处理策略。",
        TextId.TooManyExclusions => "排除目录过多，生成的命令超过安全长度。请使用更宽泛的名称或通配符后重试。",
        TextId.CannotReadDirectory => "无法读取目录，已按排除处理：{0} ({1})",
        TextId.CannotReadDirectoryAttributes => "无法读取目录属性，已按排除处理：{0} ({1})",
        TextId.MoveFollowForbidden => "移动时不能跟随链接目标，否则可能删除源目录树之外的文件。请改为跳过链接或复制链接本身。",
        TextId.RootLinkForbidden => "源目录本身是链接或联接点，Robocopy 不会对根链接应用跳过/复制链接策略。请改选实际目录，或仅在复制操作中明确选择跟随链接目标。",
        TextId.OptionLikeExclusion => "{0}项不能以 / 开头，否则可能被 Robocopy 解释为命令开关：{1}",
        TextId.SelectNamedDirectory => "请选择{0}。",
        TextId.NamedDirectoryMissing => "{0}不存在：{1}",
        TextId.SelectDestinationDirectory => "请选择目标目录。",
        TextId.SameSourceDestination => "源目录与目标目录不能相同。",
        TextId.DestinationInsideSource => "目标目录不能位于源目录内部，否则复制会递归进入自身。",
        TextId.CannotStartRobocopy => "无法启动 robocopy.exe。",
        TextId.ClipboardNoPasteDirectory => "剪贴板中没有可粘贴的目录。",
        TextId.MoveIntoSelf => "源目录已经位于该目标目录中，无法移动到自身。",
        TextId.ClipboardSourceMissing => "剪贴板源目录不存在：{0}",
        TextId.ClipboardNoDirectory => "剪贴板中没有目录。请先使用资源管理器或 Robocopy 安全复制右键菜单进行复制/剪切。",
        TextId.ClipboardMultipleItems => "当前版本一次只支持一个目录，剪贴板中有 {0:N0} 个项目。",
        TextId.CopySuffix => "{0} - 副本",
        TextId.CopySuffixIndexed => "{0} - 副本 ({1})",
        TextId.ModeOnlyCopyMove => "--mode 只接受 copy 或 move。",
        TextId.SpecialActionsConflict => "安装、移除、暂存、粘贴、帮助和版本命令不能同时使用。",
        TextId.StageRequiresMode => "--stage-source 必须同时指定 --mode copy 或 move。",
        TextId.PasteCannotCombine => "--paste-to 不能与源、目标或模式参数同时使用。",
        TextId.OptionMissingValue => "{0} 缺少参数值。",
        TextId.ContextTargetMissing => "右键菜单目标程序不存在。",
        TextId.RegistryCreateFailed => "无法创建注册表项：HKCU\\{0}",
        TextId.ContextCommandCreateFailed => "无法创建右键菜单命令：{0}",
        TextId.ContextCommandLineCreateFailed => "无法创建右键菜单命令行：{0}",
        TextId.ContextMenuTitle => "Robocopy 安全复制",
        TextId.ContextCopyThisDirectory => "复制此目录",
        TextId.ContextCopyCurrentDirectory => "复制当前目录",
        TextId.ContextCutThisDirectory => "剪切此目录",
        TextId.ContextCutCurrentDirectory => "剪切当前目录",
        TextId.ContextPasteThisDirectory => "粘贴到此目录...",
        TextId.ContextPasteCurrentDirectory => "粘贴到当前目录...",
        TextId.ContextOpen => "打开安全复制...",
        TextId.UnknownOption => "未知参数：{0}",
        TextId.HelpText => "用法：\n  {0} [--source <路径>] [--destination <路径>] [--mode copy|move]\n  {0} --install-context-menu\n  {0} --uninstall-context-menu\n  {0} --stage-source <路径> --mode copy|move\n  {0} --paste-to <路径>\n  {0} --help | --version",
        TextId.VersionText => "{0} 版本 {1}",
        _ => throw new ArgumentOutOfRangeException(nameof(id), id, null),
    };
}
